name: Check README content

on:
  push:
    paths:
      - README.md
  pull_request:
    paths:
      - README.md

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if README contains 'Project Overview'
        run: |
          if ! grep -q "Project Overview" README.md; then
            echo "README.md does not contain 'Project Overview'. Please add the required heading."
            exit 1
          else
            echo "README.md contains 'Project Overview'."
          fi

      - name: Check if README contains 'install' keyword
        run: |
          if ! grep -iq "install" README.md; then
            echo "README.md does not contain the 'install' keyword. Please ensure installation instructions are included."
            exit 1
          else
            echo "README.md contains 'install' keyword."
          fi

      - name: Check if README contains 'usage' keyword
        run: |
          if ! grep -iq "usage" README.md; then
            echo "README.md does not contain the 'usage' keyword. Please include usage instructions."
            exit 1
          else
            echo "README.md contains 'usage' keyword."
          fi